name: v3 
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - nodejs
  - jupyterlab>=2.0.0
  - numpy>=1.18.1
  - h5py
  - scipy>=1.3.0
  - dask=2.20.0
  - dask-labextension>=2.0.0
  - notebook
  - matplotlib
  - pandas>=1.0.1
  - tensorflow
  - pytorch
  - pip:
    - torchsummary
    - pandarallel
